# Generated by Django 4.0.1 on 2023-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calling',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False, verbose_name='レベル')),
                ('call', models.CharField(max_length=10, verbose_name='コール')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'calling',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from', models.CharField(max_length=8, verbose_name='お気に入り元ID')),
                ('id_to', models.CharField(max_length=8, verbose_name='お気に入り先ID')),
                ('vs', models.IntegerField(default=0, verbose_name='対戦回数')),
                ('win', models.IntegerField(default=0, verbose_name='勝ち数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'friend',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('rank', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='ランク')),
                ('lower_limit', models.IntegerField(verbose_name='ポイント下限')),
                ('upper_limit', models.IntegerField(verbose_name='ポイント上限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='メールアドレス')),
                ('win_cpu', models.IntegerField(default=0, null=True, verbose_name='勝ち総ポイント(CPU)')),
                ('win_count', models.IntegerField(default=0, null=True, verbose_name='勝ち数')),
                ('lose_cpu', models.IntegerField(default=0, null=True, verbose_name='負け総ポイント(CPU)')),
                ('draw_cpu', models.IntegerField(default=0, null=True, verbose_name='引き分け総ポイント(CPU)')),
                ('win_friend', models.IntegerField(default=0, null=True, verbose_name='勝ち総ポイント(フレンド)')),
                ('lose_friend', models.IntegerField(default=0, null=True, verbose_name='負け総ポイント(フレンド)')),
                ('draw_friend', models.IntegerField(default=0, null=True, verbose_name='引き分け総ポイント(フレンド)')),
                ('flag', models.BooleanField(default=False, verbose_name='ユーザーフラグ')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
                ('recent_login_at', models.DateTimeField(default='2022-01-01 00:00:00', verbose_name='最終ログイン日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('id_from', 'id_to'), name='unique_stock'),
        ),
    ]
