create database if not exists numeron;
use numeron;
drop table if exists auth_group_permissions;
drop table if exists auth_user_groups;
drop table if exists auth_user_user_permissions;
drop table if exists django_admin_log;
drop table if exists django_migrations;
drop table if exists django_session;
drop table if exists auth_permission;
drop table if exists auth_group;
drop table if exists auth_user;
drop table if exists django_content_type;
drop table if exists user;
drop table if exists ranking;
drop table if exists friend;
drop table if exists calling;